server:
  port: 8082

spring:
  application:
    name: plazoleta-service
  
  datasource:
    url: jdbc:postgresql://localhost:5433/plazoleta_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# JWT Configuration (must match usuarios-service)
jwt:
  secret: ${JWT_SECRET:bb7fd9ad778c38c5d0ed3f6f126b09652ea4e730c837d139f91ddb74f4720319}

# OpenAPI / Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# Feign Clients
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

# URLs de microservicios
microservices:
  usuarios:
    url: ${USUARIOS_SERVICE_URL:http://localhost:8081}
  trazabilidad:
    url: ${TRAZABILIDAD_SERVICE_URL:http://localhost:8083}
  mensajeria:
    url: ${MENSAJERIA_SERVICE_URL:http://localhost:8084}
